### PR TITLE
Change in the .dot file label generation.

### PR DESCRIPTION
**Pull request by tothimre-zz**
Instead of new line characters it delimits the lables with "->" and "-->>" strings.

The reason I did it because the graphviz did contain only the first line of the label.

### CODE REVIEW

**Comment by Trismegiste** [comment]
Hello,

thanks for the pull request but before I'll make this change I have a question : 
- What software do you use for rendering DOT ? Because with Xdot under linux and Graphviz under windows I have no problem :question: 

=> http://www.graphviz.org/Download..php

**Comment by tothimre-zz** [comment]
Hello,
I use the latest Ubuntu, I use Graphviz and it's 'dot' command.
I only got this graph without this modification:

sample

As you can see it only show the abbreviated name spaces only.
If you wish to take my change label delimiters to different strings, but in my case the new line character does not work at all.

Thanks for considerring.

Imre

**Comment by Trismegiste** [comment]
That's very strange, I've made a try just now : 

``` bash
$ php mondrian.php spa --cycle .
$ dot -Tpng -O report.dot
```

And I got this : 

report dot

I wonder if there could be a bug in my modified release of alom/graphviz. Can you check the content of the dot file please ?

Labels look like like this : 

```
label="TMA\nLiskovSearch"
```

or look like this : 

```
label="TMA
LiskovSearch"
```

I think this could be a problem of "\n" escaping. In fact I really want to know where does the bug come because with the change you propose, labels could be too large to enter in the box.

Can you try with the phar release (in the Resources/box directory) ?

**Comment by tothimre-zz** [comment]
Hello,

Of course this was the first of the process and indeed it looked like the second version. now I have changed my commit. It seems it works good now.

I think it is good to use constants instead of typing things again and again. makes refactoring easier, and not at last kills duplication;)

have Fun!

Imre

**Comment by Trismegiste** [comment]
You're damn right about the constant :smiley: 

Frankly, this part of my app was fast coded. Thank you for pointing out this bug :+1: 
One last question : the constant is in StaticAnalyzer and the subclass ImplVertex too. Was your intention ?

I try to merge this PR today or tomorow.

**Comment by tothimre-zz** [comment]
I will find a good place for it today ( I am at Amsterdam at the moment ), if I have it I let you know :) for sure constants shall not be duplicated too :) I did because when it was one line '-->>' '->' strings looked cooler, but now it is pointless.

Great project, I think I will further contribute if you don;t mind.

I have 2 ideas:
  -Each source of the arrows shall have a color code and all arrows coming form this source will be this color (this shall be a commandline switch I suppose).

  -Maybe there shall have an option where classes was in the same group form their workspace.

What do you think?

**Comment by tothimre-zz** [comment]
I think now it is good, if you think so too you might pull it.

Imre

**Comment by Trismegiste** [comment]
Ok I have figured out why it works with me and not with you. The problem was a misconfiguration of... composer.json. It's confusing and a little bit silly.

Since the "\n" was not escaped, I have added a commit in alom/graphviz to escape them and I have overridden the repository config in composer.json to target my forked release of alom/graphviz. 

BUT, the url of my fork was the read-write github url, not the public read-only. Since I have the github API ssl key on my computers, I didn't notice the problem, but other users get the fallback original release, without the escaped "\n"

I'm intend to correct this, ASAP. Sorry for this failure.

Once again, I have proved the "developer axiom" : "It works on my computer" :smile:

**Pull request merged**
